name: mangareader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  
  http: ^1.2.0 # For making HTTP requests 
  provider: ^6.0.5 # State management
  cached_network_image: ^3.2.3 #  For image caching
  flutter_spinkit: ^5.1.0  # Loading indicators
  shared_preferences: ^2.1.1 # For local storage
  url_launcher: ^6.1.10 # To open URLs in the browser
  photo_view: ^0.15.0 # For image zooming

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
